name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x # Run with latest stable Deno.
      - run: deno fmt --check server/
      - run: deno lint server/
      #- run: deno test --allow-all --coverage cov/
      #- run: deno coverage --lcov cov/ > cov.lcov


      